//
//Copyright Manetu Inc. All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: manetu/policyengine/events/v1/message.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessRecord_Decision int32

const (
	AccessRecord_UNSPECIFIED AccessRecord_Decision = 0
	AccessRecord_GRANT       AccessRecord_Decision = 1
	AccessRecord_DENY        AccessRecord_Decision = 2
)

// Enum value maps for AccessRecord_Decision.
var (
	AccessRecord_Decision_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "GRANT",
		2: "DENY",
	}
	AccessRecord_Decision_value = map[string]int32{
		"UNSPECIFIED": 0,
		"GRANT":       1,
		"DENY":        2,
	}
)

func (x AccessRecord_Decision) Enum() *AccessRecord_Decision {
	p := new(AccessRecord_Decision)
	*p = x
	return p
}

func (x AccessRecord_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRecord_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_manetu_policyengine_events_v1_message_proto_enumTypes[0].Descriptor()
}

func (AccessRecord_Decision) Type() protoreflect.EnumType {
	return &file_manetu_policyengine_events_v1_message_proto_enumTypes[0]
}

func (x AccessRecord_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRecord_Decision.Descriptor instead.
func (AccessRecord_Decision) EnumDescriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 0}
}

type AccessRecord_BypassGrantReason int32

const (
	AccessRecord_NOT_GRANTED  AccessRecord_BypassGrantReason = 0
	AccessRecord_PUBLIC       AccessRecord_BypassGrantReason = 1
	AccessRecord_VISITOR      AccessRecord_BypassGrantReason = 2
	AccessRecord_ANTI_LOCKOUT AccessRecord_BypassGrantReason = 3
)

// Enum value maps for AccessRecord_BypassGrantReason.
var (
	AccessRecord_BypassGrantReason_name = map[int32]string{
		0: "NOT_GRANTED",
		1: "PUBLIC",
		2: "VISITOR",
		3: "ANTI_LOCKOUT",
	}
	AccessRecord_BypassGrantReason_value = map[string]int32{
		"NOT_GRANTED":  0,
		"PUBLIC":       1,
		"VISITOR":      2,
		"ANTI_LOCKOUT": 3,
	}
)

func (x AccessRecord_BypassGrantReason) Enum() *AccessRecord_BypassGrantReason {
	p := new(AccessRecord_BypassGrantReason)
	*p = x
	return p
}

func (x AccessRecord_BypassGrantReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRecord_BypassGrantReason) Descriptor() protoreflect.EnumDescriptor {
	return file_manetu_policyengine_events_v1_message_proto_enumTypes[1].Descriptor()
}

func (AccessRecord_BypassGrantReason) Type() protoreflect.EnumType {
	return &file_manetu_policyengine_events_v1_message_proto_enumTypes[1]
}

func (x AccessRecord_BypassGrantReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRecord_BypassGrantReason.Descriptor instead.
func (AccessRecord_BypassGrantReason) EnumDescriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 1}
}

type AccessRecord_BypassDenyReason int32

const (
	AccessRecord_NOT_DENIED        AccessRecord_BypassDenyReason = 0
	AccessRecord_JWT_REQUIRED      AccessRecord_BypassDenyReason = 1
	AccessRecord_OPERATOR_REQUIRED AccessRecord_BypassDenyReason = 2
)

// Enum value maps for AccessRecord_BypassDenyReason.
var (
	AccessRecord_BypassDenyReason_name = map[int32]string{
		0: "NOT_DENIED",
		1: "JWT_REQUIRED",
		2: "OPERATOR_REQUIRED",
	}
	AccessRecord_BypassDenyReason_value = map[string]int32{
		"NOT_DENIED":        0,
		"JWT_REQUIRED":      1,
		"OPERATOR_REQUIRED": 2,
	}
)

func (x AccessRecord_BypassDenyReason) Enum() *AccessRecord_BypassDenyReason {
	p := new(AccessRecord_BypassDenyReason)
	*p = x
	return p
}

func (x AccessRecord_BypassDenyReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRecord_BypassDenyReason) Descriptor() protoreflect.EnumDescriptor {
	return file_manetu_policyengine_events_v1_message_proto_enumTypes[2].Descriptor()
}

func (AccessRecord_BypassDenyReason) Type() protoreflect.EnumType {
	return &file_manetu_policyengine_events_v1_message_proto_enumTypes[2]
}

func (x AccessRecord_BypassDenyReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRecord_BypassDenyReason.Descriptor instead.
func (AccessRecord_BypassDenyReason) EnumDescriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 2}
}

type AccessRecord_BundleReference_Phase int32

const (
	AccessRecord_BundleReference_UNSPECIFIED AccessRecord_BundleReference_Phase = 0
	AccessRecord_BundleReference_SYSTEM      AccessRecord_BundleReference_Phase = 1
	AccessRecord_BundleReference_IDENTITY    AccessRecord_BundleReference_Phase = 2
	AccessRecord_BundleReference_RESOURCE    AccessRecord_BundleReference_Phase = 3
	AccessRecord_BundleReference_SCOPE       AccessRecord_BundleReference_Phase = 4
)

// Enum value maps for AccessRecord_BundleReference_Phase.
var (
	AccessRecord_BundleReference_Phase_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SYSTEM",
		2: "IDENTITY",
		3: "RESOURCE",
		4: "SCOPE",
	}
	AccessRecord_BundleReference_Phase_value = map[string]int32{
		"UNSPECIFIED": 0,
		"SYSTEM":      1,
		"IDENTITY":    2,
		"RESOURCE":    3,
		"SCOPE":       4,
	}
)

func (x AccessRecord_BundleReference_Phase) Enum() *AccessRecord_BundleReference_Phase {
	p := new(AccessRecord_BundleReference_Phase)
	*p = x
	return p
}

func (x AccessRecord_BundleReference_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRecord_BundleReference_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_manetu_policyengine_events_v1_message_proto_enumTypes[3].Descriptor()
}

func (AccessRecord_BundleReference_Phase) Type() protoreflect.EnumType {
	return &file_manetu_policyengine_events_v1_message_proto_enumTypes[3]
}

func (x AccessRecord_BundleReference_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRecord_BundleReference_Phase.Descriptor instead.
func (AccessRecord_BundleReference_Phase) EnumDescriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 3, 0}
}

type AccessRecord_BundleReference_ReasonCode int32

const (
	AccessRecord_BundleReference_POLICY_OUTCOME    AccessRecord_BundleReference_ReasonCode = 0
	AccessRecord_BundleReference_COMPILATION_ERROR AccessRecord_BundleReference_ReasonCode = 1   // Policy compilation error
	AccessRecord_BundleReference_NOTFOUND_ERROR    AccessRecord_BundleReference_ReasonCode = 2   // One or more policy references could not be found
	AccessRecord_BundleReference_NETWORK_ERROR     AccessRecord_BundleReference_ReasonCode = 3   // A network error prevented the resolution of policy
	AccessRecord_BundleReference_EVALUATION_ERROR  AccessRecord_BundleReference_ReasonCode = 4   // An error reported by OPA Policy evaluator (excluding compilation error)
	AccessRecord_BundleReference_INVALPARAM_ERROR  AccessRecord_BundleReference_ReasonCode = 5   // Invalid parameter or identifier
	AccessRecord_BundleReference_UNKNOWN_ERROR     AccessRecord_BundleReference_ReasonCode = 100 // An unspecified error was encountered
)

// Enum value maps for AccessRecord_BundleReference_ReasonCode.
var (
	AccessRecord_BundleReference_ReasonCode_name = map[int32]string{
		0:   "POLICY_OUTCOME",
		1:   "COMPILATION_ERROR",
		2:   "NOTFOUND_ERROR",
		3:   "NETWORK_ERROR",
		4:   "EVALUATION_ERROR",
		5:   "INVALPARAM_ERROR",
		100: "UNKNOWN_ERROR",
	}
	AccessRecord_BundleReference_ReasonCode_value = map[string]int32{
		"POLICY_OUTCOME":    0,
		"COMPILATION_ERROR": 1,
		"NOTFOUND_ERROR":    2,
		"NETWORK_ERROR":     3,
		"EVALUATION_ERROR":  4,
		"INVALPARAM_ERROR":  5,
		"UNKNOWN_ERROR":     100,
	}
)

func (x AccessRecord_BundleReference_ReasonCode) Enum() *AccessRecord_BundleReference_ReasonCode {
	p := new(AccessRecord_BundleReference_ReasonCode)
	*p = x
	return p
}

func (x AccessRecord_BundleReference_ReasonCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessRecord_BundleReference_ReasonCode) Descriptor() protoreflect.EnumDescriptor {
	return file_manetu_policyengine_events_v1_message_proto_enumTypes[4].Descriptor()
}

func (AccessRecord_BundleReference_ReasonCode) Type() protoreflect.EnumType {
	return &file_manetu_policyengine_events_v1_message_proto_enumTypes[4]
}

func (x AccessRecord_BundleReference_ReasonCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessRecord_BundleReference_ReasonCode.Descriptor instead.
func (AccessRecord_BundleReference_ReasonCode) EnumDescriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 3, 1}
}

type AccessRecord struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Metadata       *AccessRecord_Metadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Principal      *AccessRecord_Principal         `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Operation      string                          `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`                                                         // from PORC, e.g. "http-post", "graphql-mutate", etc
	Resource       string                          `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`                                                           // MRN from PORC e.g. "mrn:http:/foo"
	Decision       AccessRecord_Decision           `protobuf:"varint,5,opt,name=decision,proto3,enum=manetu.policyengine.events.v1.AccessRecord_Decision" json:"decision,omitempty"` // At least one policy must return allow=true to GRANT
	References     []*AccessRecord_BundleReference `protobuf:"bytes,6,rep,name=references,proto3" json:"references,omitempty"`                                                       // The list of any policy-bundles consulted in formulating outcome
	Porc           string                          `protobuf:"bytes,7,opt,name=porc,proto3" json:"porc,omitempty"`                                                                   // fully realized porc.json
	SystemOverride bool                            `protobuf:"varint,8,opt,name=system_override,json=systemOverride,proto3" json:"system_override,omitempty"`                        // System/phase1 decision bypass
	// Types that are valid to be assigned to OverrideReason:
	//
	//	*AccessRecord_GrantReason
	//	*AccessRecord_DenyReason
	OverrideReason isAccessRecord_OverrideReason `protobuf_oneof:"override_reason"`
	Duration       *AccessRecord_Duration        `protobuf:"bytes,11,opt,name=duration,proto3" json:"duration,omitempty"` // execution latency, in nanoseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccessRecord) Reset() {
	*x = AccessRecord{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecord) ProtoMessage() {}

func (x *AccessRecord) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecord.ProtoReflect.Descriptor instead.
func (*AccessRecord) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *AccessRecord) GetMetadata() *AccessRecord_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccessRecord) GetPrincipal() *AccessRecord_Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *AccessRecord) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AccessRecord) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AccessRecord) GetDecision() AccessRecord_Decision {
	if x != nil {
		return x.Decision
	}
	return AccessRecord_UNSPECIFIED
}

func (x *AccessRecord) GetReferences() []*AccessRecord_BundleReference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *AccessRecord) GetPorc() string {
	if x != nil {
		return x.Porc
	}
	return ""
}

func (x *AccessRecord) GetSystemOverride() bool {
	if x != nil {
		return x.SystemOverride
	}
	return false
}

func (x *AccessRecord) GetOverrideReason() isAccessRecord_OverrideReason {
	if x != nil {
		return x.OverrideReason
	}
	return nil
}

func (x *AccessRecord) GetGrantReason() AccessRecord_BypassGrantReason {
	if x != nil {
		if x, ok := x.OverrideReason.(*AccessRecord_GrantReason); ok {
			return x.GrantReason
		}
	}
	return AccessRecord_NOT_GRANTED
}

func (x *AccessRecord) GetDenyReason() AccessRecord_BypassDenyReason {
	if x != nil {
		if x, ok := x.OverrideReason.(*AccessRecord_DenyReason); ok {
			return x.DenyReason
		}
	}
	return AccessRecord_NOT_DENIED
}

func (x *AccessRecord) GetDuration() *AccessRecord_Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type isAccessRecord_OverrideReason interface {
	isAccessRecord_OverrideReason()
}

type AccessRecord_GrantReason struct {
	GrantReason AccessRecord_BypassGrantReason `protobuf:"varint,9,opt,name=grant_reason,json=grantReason,proto3,enum=manetu.policyengine.events.v1.AccessRecord_BypassGrantReason,oneof"`
}

type AccessRecord_DenyReason struct {
	DenyReason AccessRecord_BypassDenyReason `protobuf:"varint,10,opt,name=deny_reason,json=denyReason,proto3,enum=manetu.policyengine.events.v1.AccessRecord_BypassDenyReason,oneof"`
}

func (*AccessRecord_GrantReason) isAccessRecord_OverrideReason() {}

func (*AccessRecord_DenyReason) isAccessRecord_OverrideReason() {}

type Integrity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeafHash      []byte                 `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	SigAlg        string                 `protobuf:"bytes,4,opt,name=sig_alg,json=sigAlg,proto3" json:"sig_alg,omitempty"` // "Ed25519" / "ECDSA-RFC6979"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integrity) Reset() {
	*x = Integrity{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrity) ProtoMessage() {}

func (x *Integrity) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrity.ProtoReflect.Descriptor instead.
func (*Integrity) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Integrity) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

func (x *Integrity) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Integrity) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Integrity) GetSigAlg() string {
	if x != nil {
		return x.SigAlg
	}
	return ""
}

// Canonical bytes = verbatim record_pb bytes from the upstream accesslog topic.
// leaf_hash = SHA-256(record_pb).  Do NOT re-encode.
type SignedAccessRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordPb      []byte                 `protobuf:"bytes,1,opt,name=record_pb,json=recordPb,proto3" json:"record_pb,omitempty"` // verbatim AccessRecord bytes, untouched
	Integrity     *Integrity             `protobuf:"bytes,2,opt,name=integrity,proto3" json:"integrity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedAccessRecord) Reset() {
	*x = SignedAccessRecord{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedAccessRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedAccessRecord) ProtoMessage() {}

func (x *SignedAccessRecord) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedAccessRecord.ProtoReflect.Descriptor instead.
func (*SignedAccessRecord) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *SignedAccessRecord) GetRecordPb() []byte {
	if x != nil {
		return x.RecordPb
	}
	return nil
}

func (x *SignedAccessRecord) GetIntegrity() *Integrity {
	if x != nil {
		return x.Integrity
	}
	return nil
}

type AccessRecord_Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // optional contextual name/value pairs e.g. "k8s-pod" = "mcp-attribute-serviec-gw-123123"
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                                                                             // a UUID for this record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRecord_Metadata) Reset() {
	*x = AccessRecord_Metadata{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRecord_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecord_Metadata) ProtoMessage() {}

func (x *AccessRecord_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecord_Metadata.ProtoReflect.Descriptor instead.
func (*AccessRecord_Metadata) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AccessRecord_Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AccessRecord_Metadata) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AccessRecord_Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AccessRecord_Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRecord_Principal) Reset() {
	*x = AccessRecord_Principal{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRecord_Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecord_Principal) ProtoMessage() {}

func (x *AccessRecord_Principal) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecord_Principal.ProtoReflect.Descriptor instead.
func (*AccessRecord_Principal) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AccessRecord_Principal) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AccessRecord_Principal) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

type AccessRecord_PolicyReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mrn           string                 `protobuf:"bytes,1,opt,name=mrn,proto3" json:"mrn,omitempty"` // mrn+fingerprint uniquely identify the policy document
	Fingerprint   []byte                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRecord_PolicyReference) Reset() {
	*x = AccessRecord_PolicyReference{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRecord_PolicyReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecord_PolicyReference) ProtoMessage() {}

func (x *AccessRecord_PolicyReference) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecord_PolicyReference.ProtoReflect.Descriptor instead.
func (*AccessRecord_PolicyReference) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 2}
}

func (x *AccessRecord_PolicyReference) GetMrn() string {
	if x != nil {
		return x.Mrn
	}
	return ""
}

func (x *AccessRecord_PolicyReference) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

type AccessRecord_BundleReference struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Id            string                                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // operation or role-mrn
	Policies      []*AccessRecord_PolicyReference         `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	Decision      AccessRecord_Decision                   `protobuf:"varint,3,opt,name=decision,proto3,enum=manetu.policyengine.events.v1.AccessRecord_Decision" json:"decision,omitempty"`        // The outcome of this specific policy-bundle
	Phase         AccessRecord_BundleReference_Phase      `protobuf:"varint,4,opt,name=phase,proto3,enum=manetu.policyengine.events.v1.AccessRecord_BundleReference_Phase" json:"phase,omitempty"` // The conjunction phase
	ReasonCode    AccessRecord_BundleReference_ReasonCode `protobuf:"varint,5,opt,name=reason_code,json=reasonCode,proto3,enum=manetu.policyengine.events.v1.AccessRecord_BundleReference_ReasonCode" json:"reason_code,omitempty"`
	Reason        string                                  `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`      // optional reason description, typically used for exception scenarios such as COMPILATION_ERROR
	Duration      uint64                                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"` // execution latency, in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRecord_BundleReference) Reset() {
	*x = AccessRecord_BundleReference{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRecord_BundleReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecord_BundleReference) ProtoMessage() {}

func (x *AccessRecord_BundleReference) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecord_BundleReference.ProtoReflect.Descriptor instead.
func (*AccessRecord_BundleReference) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 3}
}

func (x *AccessRecord_BundleReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessRecord_BundleReference) GetPolicies() []*AccessRecord_PolicyReference {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *AccessRecord_BundleReference) GetDecision() AccessRecord_Decision {
	if x != nil {
		return x.Decision
	}
	return AccessRecord_UNSPECIFIED
}

func (x *AccessRecord_BundleReference) GetPhase() AccessRecord_BundleReference_Phase {
	if x != nil {
		return x.Phase
	}
	return AccessRecord_BundleReference_UNSPECIFIED
}

func (x *AccessRecord_BundleReference) GetReasonCode() AccessRecord_BundleReference_ReasonCode {
	if x != nil {
		return x.ReasonCode
	}
	return AccessRecord_BundleReference_POLICY_OUTCOME
}

func (x *AccessRecord_BundleReference) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AccessRecord_BundleReference) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type AccessRecord_Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overall       uint64                 `protobuf:"varint,1,opt,name=overall,proto3" json:"overall,omitempty"`
	Phases        map[uint32]uint64      `protobuf:"bytes,2,rep,name=phases,proto3" json:"phases,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRecord_Duration) Reset() {
	*x = AccessRecord_Duration{}
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRecord_Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecord_Duration) ProtoMessage() {}

func (x *AccessRecord_Duration) ProtoReflect() protoreflect.Message {
	mi := &file_manetu_policyengine_events_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecord_Duration.ProtoReflect.Descriptor instead.
func (*AccessRecord_Duration) Descriptor() ([]byte, []int) {
	return file_manetu_policyengine_events_v1_message_proto_rawDescGZIP(), []int{0, 4}
}

func (x *AccessRecord_Duration) GetOverall() uint64 {
	if x != nil {
		return x.Overall
	}
	return 0
}

func (x *AccessRecord_Duration) GetPhases() map[uint32]uint64 {
	if x != nil {
		return x.Phases
	}
	return nil
}

var File_manetu_policyengine_events_v1_message_proto protoreflect.FileDescriptor

const file_manetu_policyengine_events_v1_message_proto_rawDesc = "" +
	"\n" +
	"+manetu/policyengine/events/v1/message.proto\x12\x1dmanetu.policyengine.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x11\n" +
	"\fAccessRecord\x12P\n" +
	"\bmetadata\x18\x01 \x01(\v24.manetu.policyengine.events.v1.AccessRecord.MetadataR\bmetadata\x12S\n" +
	"\tprincipal\x18\x02 \x01(\v25.manetu.policyengine.events.v1.AccessRecord.PrincipalR\tprincipal\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12P\n" +
	"\bdecision\x18\x05 \x01(\x0e24.manetu.policyengine.events.v1.AccessRecord.DecisionR\bdecision\x12[\n" +
	"\n" +
	"references\x18\x06 \x03(\v2;.manetu.policyengine.events.v1.AccessRecord.BundleReferenceR\n" +
	"references\x12\x12\n" +
	"\x04porc\x18\a \x01(\tR\x04porc\x12'\n" +
	"\x0fsystem_override\x18\b \x01(\bR\x0esystemOverride\x12b\n" +
	"\fgrant_reason\x18\t \x01(\x0e2=.manetu.policyengine.events.v1.AccessRecord.BypassGrantReasonH\x00R\vgrantReason\x12_\n" +
	"\vdeny_reason\x18\n" +
	" \x01(\x0e2<.manetu.policyengine.events.v1.AccessRecord.BypassDenyReasonH\x00R\n" +
	"denyReason\x12P\n" +
	"\bduration\x18\v \x01(\v24.manetu.policyengine.events.v1.AccessRecord.DurationR\bduration\x1a\xdd\x01\n" +
	"\bMetadata\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12O\n" +
	"\x03env\x18\x02 \x03(\v2=.manetu.policyengine.events.v1.AccessRecord.Metadata.EnvEntryR\x03env\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\tPrincipal\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x1aE\n" +
	"\x0fPolicyReference\x12\x10\n" +
	"\x03mrn\x18\x01 \x01(\tR\x03mrn\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\fR\vfingerprint\x1a\xaf\x05\n" +
	"\x0fBundleReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12W\n" +
	"\bpolicies\x18\x02 \x03(\v2;.manetu.policyengine.events.v1.AccessRecord.PolicyReferenceR\bpolicies\x12P\n" +
	"\bdecision\x18\x03 \x01(\x0e24.manetu.policyengine.events.v1.AccessRecord.DecisionR\bdecision\x12W\n" +
	"\x05phase\x18\x04 \x01(\x0e2A.manetu.policyengine.events.v1.AccessRecord.BundleReference.PhaseR\x05phase\x12g\n" +
	"\vreason_code\x18\x05 \x01(\x0e2F.manetu.policyengine.events.v1.AccessRecord.BundleReference.ReasonCodeR\n" +
	"reasonCode\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1a\n" +
	"\bduration\x18\a \x01(\x04R\bduration\"K\n" +
	"\x05Phase\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\f\n" +
	"\bIDENTITY\x10\x02\x12\f\n" +
	"\bRESOURCE\x10\x03\x12\t\n" +
	"\x05SCOPE\x10\x04\"\x9d\x01\n" +
	"\n" +
	"ReasonCode\x12\x12\n" +
	"\x0ePOLICY_OUTCOME\x10\x00\x12\x15\n" +
	"\x11COMPILATION_ERROR\x10\x01\x12\x12\n" +
	"\x0eNOTFOUND_ERROR\x10\x02\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x03\x12\x14\n" +
	"\x10EVALUATION_ERROR\x10\x04\x12\x14\n" +
	"\x10INVALPARAM_ERROR\x10\x05\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10d\x1a\xb9\x01\n" +
	"\bDuration\x12\x18\n" +
	"\aoverall\x18\x01 \x01(\x04R\aoverall\x12X\n" +
	"\x06phases\x18\x02 \x03(\v2@.manetu.policyengine.events.v1.AccessRecord.Duration.PhasesEntryR\x06phases\x1a9\n" +
	"\vPhasesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"0\n" +
	"\bDecision\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GRANT\x10\x01\x12\b\n" +
	"\x04DENY\x10\x02\"O\n" +
	"\x11BypassGrantReason\x12\x0f\n" +
	"\vNOT_GRANTED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\v\n" +
	"\aVISITOR\x10\x02\x12\x10\n" +
	"\fANTI_LOCKOUT\x10\x03\"K\n" +
	"\x10BypassDenyReason\x12\x0e\n" +
	"\n" +
	"NOT_DENIED\x10\x00\x12\x10\n" +
	"\fJWT_REQUIRED\x10\x01\x12\x15\n" +
	"\x11OPERATOR_REQUIRED\x10\x02B\x11\n" +
	"\x0foverride_reason\"v\n" +
	"\tIntegrity\x12\x1b\n" +
	"\tleaf_hash\x18\x01 \x01(\fR\bleafHash\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x17\n" +
	"\asig_alg\x18\x04 \x01(\tR\x06sigAlg\"y\n" +
	"\x12SignedAccessRecord\x12\x1b\n" +
	"\trecord_pb\x18\x01 \x01(\fR\brecordPb\x12F\n" +
	"\tintegrity\x18\x02 \x01(\v2(.manetu.policyengine.events.v1.IntegrityR\tintegrityB\x9a\x02\n" +
	"!com.manetu.policyengine.events.v1B\fMessageProtoP\x01ZPgithub.com/manetu/policyengine/pkg/protos/manetu/policyengine/events/v1;eventsv1\xa2\x02\x03MPE\xaa\x02\x1dManetu.Policyengine.Events.V1\xca\x02\x1dManetu\\Policyengine\\Events\\V1\xe2\x02)Manetu\\Policyengine\\Events\\V1\\GPBMetadata\xea\x02 Manetu::Policyengine::Events::V1b\x06proto3"

var (
	file_manetu_policyengine_events_v1_message_proto_rawDescOnce sync.Once
	file_manetu_policyengine_events_v1_message_proto_rawDescData []byte
)

func file_manetu_policyengine_events_v1_message_proto_rawDescGZIP() []byte {
	file_manetu_policyengine_events_v1_message_proto_rawDescOnce.Do(func() {
		file_manetu_policyengine_events_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manetu_policyengine_events_v1_message_proto_rawDesc), len(file_manetu_policyengine_events_v1_message_proto_rawDesc)))
	})
	return file_manetu_policyengine_events_v1_message_proto_rawDescData
}

var file_manetu_policyengine_events_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_manetu_policyengine_events_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_manetu_policyengine_events_v1_message_proto_goTypes = []any{
	(AccessRecord_Decision)(0),                   // 0: manetu.policyengine.events.v1.AccessRecord.Decision
	(AccessRecord_BypassGrantReason)(0),          // 1: manetu.policyengine.events.v1.AccessRecord.BypassGrantReason
	(AccessRecord_BypassDenyReason)(0),           // 2: manetu.policyengine.events.v1.AccessRecord.BypassDenyReason
	(AccessRecord_BundleReference_Phase)(0),      // 3: manetu.policyengine.events.v1.AccessRecord.BundleReference.Phase
	(AccessRecord_BundleReference_ReasonCode)(0), // 4: manetu.policyengine.events.v1.AccessRecord.BundleReference.ReasonCode
	(*AccessRecord)(nil),                         // 5: manetu.policyengine.events.v1.AccessRecord
	(*Integrity)(nil),                            // 6: manetu.policyengine.events.v1.Integrity
	(*SignedAccessRecord)(nil),                   // 7: manetu.policyengine.events.v1.SignedAccessRecord
	(*AccessRecord_Metadata)(nil),                // 8: manetu.policyengine.events.v1.AccessRecord.Metadata
	(*AccessRecord_Principal)(nil),               // 9: manetu.policyengine.events.v1.AccessRecord.Principal
	(*AccessRecord_PolicyReference)(nil),         // 10: manetu.policyengine.events.v1.AccessRecord.PolicyReference
	(*AccessRecord_BundleReference)(nil),         // 11: manetu.policyengine.events.v1.AccessRecord.BundleReference
	(*AccessRecord_Duration)(nil),                // 12: manetu.policyengine.events.v1.AccessRecord.Duration
	nil,                                          // 13: manetu.policyengine.events.v1.AccessRecord.Metadata.EnvEntry
	nil,                                          // 14: manetu.policyengine.events.v1.AccessRecord.Duration.PhasesEntry
	(*timestamppb.Timestamp)(nil),                // 15: google.protobuf.Timestamp
}
var file_manetu_policyengine_events_v1_message_proto_depIdxs = []int32{
	8,  // 0: manetu.policyengine.events.v1.AccessRecord.metadata:type_name -> manetu.policyengine.events.v1.AccessRecord.Metadata
	9,  // 1: manetu.policyengine.events.v1.AccessRecord.principal:type_name -> manetu.policyengine.events.v1.AccessRecord.Principal
	0,  // 2: manetu.policyengine.events.v1.AccessRecord.decision:type_name -> manetu.policyengine.events.v1.AccessRecord.Decision
	11, // 3: manetu.policyengine.events.v1.AccessRecord.references:type_name -> manetu.policyengine.events.v1.AccessRecord.BundleReference
	1,  // 4: manetu.policyengine.events.v1.AccessRecord.grant_reason:type_name -> manetu.policyengine.events.v1.AccessRecord.BypassGrantReason
	2,  // 5: manetu.policyengine.events.v1.AccessRecord.deny_reason:type_name -> manetu.policyengine.events.v1.AccessRecord.BypassDenyReason
	12, // 6: manetu.policyengine.events.v1.AccessRecord.duration:type_name -> manetu.policyengine.events.v1.AccessRecord.Duration
	6,  // 7: manetu.policyengine.events.v1.SignedAccessRecord.integrity:type_name -> manetu.policyengine.events.v1.Integrity
	15, // 8: manetu.policyengine.events.v1.AccessRecord.Metadata.timestamp:type_name -> google.protobuf.Timestamp
	13, // 9: manetu.policyengine.events.v1.AccessRecord.Metadata.env:type_name -> manetu.policyengine.events.v1.AccessRecord.Metadata.EnvEntry
	10, // 10: manetu.policyengine.events.v1.AccessRecord.BundleReference.policies:type_name -> manetu.policyengine.events.v1.AccessRecord.PolicyReference
	0,  // 11: manetu.policyengine.events.v1.AccessRecord.BundleReference.decision:type_name -> manetu.policyengine.events.v1.AccessRecord.Decision
	3,  // 12: manetu.policyengine.events.v1.AccessRecord.BundleReference.phase:type_name -> manetu.policyengine.events.v1.AccessRecord.BundleReference.Phase
	4,  // 13: manetu.policyengine.events.v1.AccessRecord.BundleReference.reason_code:type_name -> manetu.policyengine.events.v1.AccessRecord.BundleReference.ReasonCode
	14, // 14: manetu.policyengine.events.v1.AccessRecord.Duration.phases:type_name -> manetu.policyengine.events.v1.AccessRecord.Duration.PhasesEntry
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_manetu_policyengine_events_v1_message_proto_init() }
func file_manetu_policyengine_events_v1_message_proto_init() {
	if File_manetu_policyengine_events_v1_message_proto != nil {
		return
	}
	file_manetu_policyengine_events_v1_message_proto_msgTypes[0].OneofWrappers = []any{
		(*AccessRecord_GrantReason)(nil),
		(*AccessRecord_DenyReason)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manetu_policyengine_events_v1_message_proto_rawDesc), len(file_manetu_policyengine_events_v1_message_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manetu_policyengine_events_v1_message_proto_goTypes,
		DependencyIndexes: file_manetu_policyengine_events_v1_message_proto_depIdxs,
		EnumInfos:         file_manetu_policyengine_events_v1_message_proto_enumTypes,
		MessageInfos:      file_manetu_policyengine_events_v1_message_proto_msgTypes,
	}.Build()
	File_manetu_policyengine_events_v1_message_proto = out.File
	file_manetu_policyengine_events_v1_message_proto_goTypes = nil
	file_manetu_policyengine_events_v1_message_proto_depIdxs = nil
}
